### ISSUE TITLE
Search pane constant refresh/flicker on file updates, scroll to top on file update, klogg crashing 

### ISSUE THREAD

**Issue by rkriauciukas-freesat** [variar/klogg#206] opened 2020-09-18 11:08 UTC
Hi there! Let's start by saying I love Klogg - it really has good features and it helps a lot.

But there are some niggles and sometimes really annoying ones. Mainly these: 

- a) the constant refreshing and blinking of the search pane results list. It is just impossible to look at the results in detail when they keep appearing and disappearing.
- b) The constant search results list scroll kick to the top - I would prefer if it stayed in the same position on the main log file update.
- c) Klogg crashing randomly - after a long while usually, but still one second it is there on my taskbar, the next one it is gone. It also does not retain the state of previously open files if it crashes.

My klogg version: 20.9.0.661 / Windows 10 Pro

Maybe I am missing something and there is a way (configuration?) how to solve the two issues above? 
Thanks!

**Comment by variar** [comment] 2020-09-18 18:11
Hi, thanks for the feedback. 

Could you describe your workflow when a) and b) happen? 

The following are my best guesses.

Those issues looks related to auto-reloading of changed files. Unfortunately, most of my personal use cases do not involve changing log files, so this area of Klogg lacks testing. Sorry for that.

a) When Klogg detects file changes "in the middle" of file, it assumes that current search results are not relevant any more and reloads the file. If file changes "at the end" then no such reloading should happen. Sometimes file change detection gets confused. This feature will be improved in #172. On Windows polling for file changes every few seconds is enabled by default. Turning it off may reduce flickering due to reloading.

b) That's a good suggestion. After reload position in search results window should be kept. Will look into this.

c) This looks related to #199. Definitely should be fixed.

**Comment by variar** [comment] 2020-09-18 20:37
@rkriauciukas-freesat flickering should be fixed in 20.9.0.666.

**Comment by Romasato** [comment] 2020-09-19 13:07
Hi @variar , thank you for quick reply!

a) It is true, I am analyzing most of the time a log file that is constantly updated by another logger tool (I connect to a device via this logclient utility, it dumps the device log via network onto my PC, where I am analyzing it).
I think I've noticed klogg saying the file was truncated or something along those lines, but the logging tool just appends new lines to the end of file.
b) Would be nice if the scroll position stayed in the same space, so eyes would not lose the line I am looking at.
c) Awesome! If we can fix the crashes that would be great.

Also, one other thing I've noticed: the search pane (matches) sometimes show more lines that should not be matched, then updates after a while to show only the correct ones. 
And there were cases where the matching lines were duplicated - though in the log there was only one such line. 

Anyway, thank you for looking into this - appreciated!

**Comment by variar** [comment] 2020-09-19 19:26
False matches and duplicates are very likely due to the same data race as the crash. I'm investigating this issue.

**Comment by variar** [comment] 2020-09-20 21:23
@Romasato could you try builds 20.9.0.670+. There should be no flickering for log files that are only appended at the end. As for the crash/missed/duplicate search results, a can't reproduce it but there was an fairly obvious data race when searching and reindexing overlapped. However, it is a tricky one to fix. I think that in latest builds if not fixed entirely it should appear much less frequently.

**Comment by rkriauciukas-freesat** [comment] 2020-09-21 08:41
Thank you @variar - it is so much better now! No flickering and scroll position in Matches pane is retained - awesome!

One question about the "Follow File" mode: is this mode for both Main and Matches views? As soon I scroll the Matches pane, the "Follow File" is disengaged (button is not highlighted anymore) and the Main view does not follow the end of file anymore.

Also, when clicking "Reload" file button, would it make sense to re-run the matching too (i.e. when matching Auto-refresh is enabled)? Currently it would clear the Matches pane on manual file Reload.

Thanks again!

**Comment by variar** [comment] 2020-09-21 18:09
That some good news!

"Follow file" is currently enabled/disabled for both views as in original glogg. I think that logic behind this was that once user scrolled matches view, no new updates are required. There is an indicator of file changes in tab header. Once current place in match view is not needed, user can turn on "follow" mode. However, this looks like topic for discussion. Moved to separate issue.

**Closed** 2020-09-21 18:14 UTC
Labels: type: bug
