### ISSUE TITLE
Error: GPG error: https://favpackage.jfrog.io/artifactory/klogg_deb jammy Release: Signed file isn't valid

### ISSUE THREAD

**Issue by ofernandofilo** [variar/klogg#647] opened 2023-07-14 00:52 UTC
> JFrog's Free-Tier subscription has been deactivated.

source: https://landing.jfrog.com/reactivate-server/favpackage

_o/

**Comment by variar** [comment] 2023-07-14 04:39
Sad, but true. Duplicate of #613

**Closed** 2023-07-14 04:39 UTC
