### ISSUE TITLE
mimalloc crash at startup

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#358] opened 2021-07-04 03:55 UTC
System: Windows 10
Version: klogg-21.06.0.1053-x64-portable.zip

I think this issue may exist in several new versions. Only restart system can fix this.

Sorry I can't give crash report since my environment don't have internet connection.
I checked some crash files, the only useful information I got is mimalloc crashed. I didn't find a crash backtrace.
I tried start klogg  in command line with some arguments. Even `-h` and `-v` was crash, only one time `-dddd` works. So may be crash happened in early stage?
which file I can find the crash backtrace?

**Comment by variar** [comment] 2021-07-05 15:40
That is very unfortunate. Crash dumps should be in `klogg_dump` folder near the executable. To get the actual backtrace you need to download symbols for that release from github and open a minidump file in WInDbg/Visual Studio.

Could you send me the content of `klogg_dump` folder after the crash?

**Comment by variar** [comment] 2021-07-05 15:43
mimalloc gives about 10% performance boost in my usual scenarios. However, if it proves to be unstable, I'll turn it off for public builds.

**Comment by variar** [comment] 2021-07-06 18:53
I've seen several crash reports related to reading configuration at startup and crashing inside mimalloc. Build 21.07.0.1057 has some changes to mimalloc initialization, but I don't think they can fix the crash.

On the bright side one of my colleagues was able to reproduce something that looks like the same issue. We'll try to track it down.

**Comment by variar** [comment] 2021-07-07 10:02
We have some understanding of the  issue with mimalloc. If klogg is started in so-called "windows compatibility mode" then some parts of C runtime are loaded before mimalloc, and this creates conditions for memory being allocated by system allocator and freed by mimalloc, which is causing crashes. 

The worst part is that "compatibility mode" flags are not set for klogg binary, but they are inherited from the process that started klogg. For instance, Total Commander 8 running on recent Windows 10 versions causes such behavior.

I'll try to find a way to either force mimalloc or detect "compatibility" mode and disable memory allocation redirection.

**Comment by variar** [comment] 2021-07-07 10:04
It is worth noting that TBB malloc override library has a mechanism to check if memory passed to `free` has been allocated by TBB allocator, and use system's allocator for other cases. This might be possible to do in mimalloc

**Comment by xaljer** [comment] 2021-07-11 03:14
Unfortunately, I reproduce this issue in the isolate environment. I can't send dump files to outside.
If you release the fix, I can try it in my environment.

**Comment by variar** [comment] 2021-07-21 17:44
I've decided to switch back to tbb malloc. It is slower but more stable.  Please try builds 21.07.0.1064+

**Comment by xaljer** [comment] 2021-07-24 04:26
Just curious, mimalloc helps which part of performance? startup, search, or some thing else?

**Comment by variar** [comment] 2021-07-24 04:42
Search does a lot of string allocations for encoding conversion (file encoding -> QString UTF16 -> UTF8 for Hyperscan). With mimalloc on my machine search is a least 5% faster.

**Comment by xaljer** [comment] 2021-07-24 07:43
So for now, if file encoding is UTF-8, and the conversion of file encoding -> QString UTF16 -> UTF8 for Hyperscan is also needed?

**Comment by variar** [comment] 2021-07-24 10:08
Unfortunately, yes. Right now there is no fast path for utf8 text. However, encoding conversion usually takes noticeably less resources than actual regex matching. I'm thinking about improving encoding handling, but my time resources are limited at the moment.

**Comment by variar** [comment] 2021-08-01 21:31
Will close this for now. If there are still crashes with tbb malloc, please open new one.

**Closed by variar** 2021-08-01 21:31 UTC
Labels: status: ready for testing, type: crash
