### ISSUE TITLE
Build 512 fails if I open two empty files with same name from different folders

### ISSUE THREAD

**Issue by shvez** [variar/klogg#135] opened 2019-11-19 09:16 UTC
Hi there.

I just found this issue. The folder structure is a result of a bug in my code. 
[LoadBalancing...zip](https://github.com/variar/klogg/files/3862917/LoadBalancing.zip)

You may see it in zip. To reproduce the issue, please, unpack then open log file from LoadBalancing../log folder and after that from LoadBalancing../Nameserver/log

**Comment by variar** [comment] 2019-12-16 19:43
Can't reproduce on my Linux machine. Will try it on Windows at the office

**Comment by shvez** [comment] 2019-12-17 10:44
still may reproduce this on windows with build 19.12.0.525

**Comment by variar** [comment] 2019-12-19 11:28
Sorry, need more info. Files in zip archive are not empty. Unpacking it gives me this folder structure
```
LoadBalancing
    | log
        | NameServer.log
    | NameServer
        | log
            | NameServer.log
```

Is this correct the same structure that you have? Original description has double dots in folder names. Are those important?

Could you enable logging and attach log file for the issue (logs should be in %TEMP% folder)

**Comment by shvez** [comment] 2019-12-19 11:32
yes, '..' are important and they should be created when you just unpack
The structure is correct. it fails for me if I open from LoadBalancing../log and open file from NameServer/log

>Could you enable logging and attach log file for the issue (logs should be in %TEMP% folder)
I will

**Comment by shvez** [comment] 2019-12-19 11:48
[_log.zip](https://github.com/variar/klogg/files/3983395/_log.zip)
I managed to reproduce it twice. First time slightly differently.
I had klogg open already and I just opened the file from LoadBalancing../log folder using command line and klogg has closed in few seconds.

**Comment by variar** [comment] 2019-12-19 16:56
Might be fixed in 529. If klogg still crashes, please, increase log level to 5.

**Comment by shvez** [comment] 2019-12-20 08:11
[klogg_2019-12-20_10-10-13_17252.log.zip](https://github.com/variar/klogg/files/3987323/klogg_2019-12-20_10-10-13_17252.log.zip)
Unfortunately, it still fails

**Comment by variar** [comment] 2019-12-20 09:40
Thank! That last log really helped to find the core issue. It can be reproduced with these steps:
 1. Open klogg without any files.
 2. From command line run klogg and pass non-existing filename as an argument.
 3. Observer the crash.

**Comment by variar** [comment] 2019-12-20 12:47
Should be fixed in 19.12.0.534

**Comment by shvez** [comment] 2019-12-20 13:02
It does not fail anymore but file content is not shown. ;)

We probably may just ignore that issue

**Comment by variar** [comment] 2019-12-20 14:40
It crashed because passed file path was interpreted as incorrect in first place. Those dots in path are really tricky.

**Closed by variar** 2019-12-20 14:40 UTC
Labels: bug, ready for testing
