### ISSUE TITLE
Unreadable text in dark mode

### ISSUE THREAD

**Issue by castortech** [variar/klogg#264] opened 2021-03-23 18:01 UTC
See the following image regarding search results

![image](https://user-images.githubusercontent.com/85858/112195344-3bf85e00-8be0-11eb-8935-56a7600a2e84.png)

**Comment by PetbkA** [comment] 2021-04-18 05:44
**21.04.0.876-x64** - more on this on Windows 10 x64 LTSC (version 1809):
![klogg_2021-04-18_08-42-33](https://user-images.githubusercontent.com/22843816/115135556-12392800-a022-11eb-9205-da9b76271c0d.png)

**Comment by variar** [comment] 2021-04-18 06:55
@PetbkA  some recent commit must have broken icon background detection. I can reproduce it and will investigate the root cause.

**Comment by variar** [comment] 2021-04-18 16:23
I've changed regular expression error message background to dark yellow. Should be more readable.
Icon colors should also be fixed in >=21.04.0.876. Also updated QDarkStyle. Is is still far from ideal. If soweone knows of better general dark stylesheet for Qt5, please let me know.

**Comment by variar** [comment] 2021-04-26 19:55
Changed dark theme to use simple palette. Should look better in  21.4.0.902+.

**Comment by PetbkA** [comment] 2021-04-27 04:04
**klogg-21.04.0.902-x64** - looks nice. Thank you! :)

![klogg_2021-04-27_07-04-02](https://user-images.githubusercontent.com/22843816/116183595-db03fe80-a726-11eb-8750-9af0c008c979.png)

**Closed** 2021-04-27 05:09 UTC
Labels: status: ready for testing, type: bug
