### ISSUE TITLE
Crash report from build deleting log files

### ISSUE THREAD

**Issue by jeffjensen** [variar/klogg#251] opened 2021-02-19 00:26 UTC
Details for the issue
--------------------

#### What did you do?
Klogg had been running for many hours (6+?).  I ran a clean build test which deleted the log files and ran the test, recreating the log files.

-------------------------
Crash id
78ed07a0-28d0-4eb6-bf41-28ae3f28b868
-------------------------
Useful extra information
-------------------------
> Klogg version 21.01.0.822 (built from commit 0974b57) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment] 2021-02-24 19:33
Crashed inside Qt file reading code. Looks like file has been deleted in the same moment as klogg was reading it to redraw its window.

```
0   Qt5Core.dll                     0x7ffcd2708d93      QFileDevice::readLineData
1   Qt5Core.dll                     0x7ffcd270f9c3      QIODevice::readLine
2   Qt5Core.dll                     0x7ffcd270f6c7      QIODevice::readLine
3   klogg_portable.exe              0x7ff62e02eebc      LogData::doGetLineString (logdata.cpp:390)
4   klogg_portable.exe              0x7ff62e033c7e      AbstractLogData::getLineString (abstractlogdata.cpp:50)
5   klogg_portable.exe              0x7ff62dfdcc3f      AbstractLogView::drawTextArea (abstractlogview.cpp:1738)
6   klogg_portable.exe              0x7ff62dfd76e2      AbstractLogView::paintEvent (abstractlogview.cpp:792)
```

Klogg uses some WinAPI to open file without blocking others reading/writing/deleting it. This hack could cause unexpected behavior in Qt internals.

**Comment by jeffjensen** [comment] 2021-02-24 21:03
> Klogg uses some WinAPI to open file without blocking others reading/writing/deleting it. This hack could cause unexpected behavior in Qt internals.

I imagine so... and I greatly appreciate the non-blocking reading feature!!  :-)

I do this regularly and this is the first time I've seen a crash from it, so that suggests it has a very small window-of-opportunity of happening.  Not sure if it's possible or desired to wrap it for prevention.

**Comment by variar** [comment] 2021-04-06 16:30
I've changed reading code a bit in 21.04.0.844. Will close this until next reproduction to get new stack trace.

**Closed by variar** 2021-04-06 16:30 UTC
Labels: type: crash
