### ISSUE TITLE
Crash Report for issue #286

### ISSUE THREAD

**Issue by GeadSolutions** [variar/klogg#272] opened 2021-04-07 13:22 UTC
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id
3a485379-78fe-40b6-8cb9-28b5e92f0ada
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment] 2021-04-07 18:49
@GeadSolutions I am very sorry, but could you restart klogg one more time and give it a couple of minutes to run? I've just found out that on first start after the crash dumps are marked as pending for upload, but actual upload happens either an hour later or on next klogg start.

**Comment by GeadSolutions** [comment] 2021-04-07 21:01
Report sent.

**Comment by variar** [comment] 2021-04-27 05:07
Thanks. There were no obvious reasons for crashing. I've added some code to handle "out-of-memory-like" situations. Hope it helps. Could you try klogg 20.04.0.902 and upload new crash report if the issue is not fixed?

**Closed** 2021-05-10 19:42 UTC
Labels: status: ready for testing, type: crash
