### ISSUE TITLE
[feature request] Add a button in the search tab to keep current search and show a new search results in a new tab

### ISSUE THREAD

**Issue by Abay11** [variar/klogg#576] opened 2023-05-28 08:59 UTC
I would like to suggest this feature, something like this you could see in the VS IDE:
![image](https://github.com/variar/klogg/assets/22313821/49c0a299-70e5-48b4-b85e-abd3eefd235b).

**Comment by variar** [comment] 2023-06-25 21:21
I've merged the PR. However, there was one crash that could be related. I made two tabs. The removed the active one, then tried to search for something new without creating new tab. I was unable to reproduce it, unfortunately. I'm going to release a new CI build and watch crash reports from Sentry to find something related.

**Comment by variar** [comment] 2023-07-01 10:49
Can be tested in 23.06.0.1479+

**Comment by xaljer** [comment] 2023-07-01 11:34
Very useful feature! One small suggestion: When user switch to a another search result tab, klogg could auto change the contents in the search bar. So user can continue to search on the origin base. And the search content is no need to show on the tab title, which may be too long.

**Comment by variar** [comment] 2023-07-01 11:58
I am considering it, but I am not sure. Automatically changing the search expression might ruin the complex regex that user created and then by accident switched to another tab

**Comment by xaljer** [comment] 2023-07-01 13:40
> I am considering it, but I am not sure. Automatically changing the search expression might ruin the complex regex that user created and then by accident switched to another tab

Why user's regex would be ruined? user's regex must be remembered by a tab, so user can switch back. And all regex should be saved in the history, wouldn't be losted.

**Comment by variar** [comment] 2023-07-01 15:42
Search history is saved when user actually does a search. Switching between tabs case could work if tab remembers current input in regex textbox.

**Comment by variar** [comment] 2024-11-23 20:41
Closing this one to cleanup current milestones issues list. The main part has been implemented, improvements should go to new requests.

**Closed by variar** 2024-11-23 20:41 UTC
Labels: type: feature, status: ready for testing
