### ISSUE TITLE
UI Broken on Found View - Lines Number Area

### ISSUE THREAD

**Issue by paveltrafimuk** [variar/klogg#249] opened 2021-02-03 07:42 UTC
I use klogg on Mac (BigSur/Retina display) and have issue below
<img width="1012" alt="Screenshot 2021-02-03 at 10 38 51" src="https://user-images.githubusercontent.com/247147/106714151-7eec7b00-660c-11eb-90e3-69bca1acaf40.png">

**Comment by kjellericson** [comment] 2021-02-03 13:49
Additional info: I have a Mac too.  My line number area gets all black when scrolling.
Not in dark mode though.
![image](https://user-images.githubusercontent.com/7677586/106755898-f59a7000-662e-11eb-9e0a-0f40eb7df58e.png)

**Comment by variar** [comment] 2021-02-04 20:03
Hi, sorry for that. I don't have any Mac available. All testing is done in VirtualBox VM with Catalina. This looks like Qt rendering issue. Could you try switching UI theme in klogg view settings?

**Comment by kjellericson** [comment] 2021-02-05 07:01
I disabled "Qt High DPI support" with no change.
Screen dump from darkmode for reference:
![image](https://user-images.githubusercontent.com/7677586/107000352-07435b00-6788-11eb-86ac-965b7f82472b.png)

**Comment by kjellericson** [comment] 2021-02-05 07:03
Just as a note to any Qt problem.  When switching to Dark mode the drop down menu containing the styles make the "dark"-option extremely large.  Minor error for me, but I thiought it would be nice to know it (delete this comment if it is a known error).
![image](https://user-images.githubusercontent.com/7677586/107000685-93558280-6788-11eb-9581-e38c17071d2b.png)

**Comment by variar** [comment] 2021-02-05 18:30
@kjellericson unfortunately, QDarkStyleSheet has some issues with latest Qt version. Might get better with next release

**Comment by variar** [comment] 2021-04-25 20:41
I can reproduce this rendering bug in my Mac Virtual Box environment.  I'll see what can be done to fix it.

**Comment by variar** [comment] 2021-04-27 06:22
@paveltrafimuk I've changed dark style in klogg 21.04.0.902. Can't reproduce problem with line number area rendering in dark mode. Unfortunately, there still is a problem with other styles when line numbers area turns black on scroll.

**Comment by variar** [comment] 2021-04-27 07:37
Should be fixed in 21.04.0.903

**Closed** 2021-05-07 19:53 UTC
Labels: env: macos, status: ready for testing, type: bug
