### ISSUE TITLE
Bottom panel content erased after updates

### ISSUE THREAD

**Issue by federico-piazza** [variar/klogg#201] opened 2020-07-28 17:59 UTC
I'm using this version for Mac Catalina 10.15.6:

klogg 20.5.0.642
A fast, advanced log explorer.
Built 2020-05-24 from 1bdde17

The problem I have is that bottom panel content is erased after a match is found.

Here I recorded a video of the behavior:
https://streamable.com/tsrz64

**Comment by variar** [comment] 2020-09-13 15:37
This looks like erasing matches after log file has been updated somewhere in the middle. Might be caused by changes done for #172. Some verbose logs could be helpful to investigate further.

**Comment by variar** [comment] 2020-09-18 20:00
Indeed caused by switching to xxhash for speed. Sometimes it produces different result for same data.
```
indexed size        2075181, xxhash 16039638712285443401, md5 90cbe021618f9ccaa84c3143bd3f64d1
current read size 2075181, xxhash 6368880295697630930,   md5 90cbe021618f9ccaa84c3143bd3f64d1
```

**Comment by variar** [comment] 2020-09-18 20:36
@federico-piazza switching to xx64 provided stable change detection. Should work well in 20.9.0.666

**Comment by federico-piazza** [comment] 2020-09-18 20:59
@variar awesome, looking forward for the evil version

**Comment by variar** [comment] 2020-09-18 21:21
This evil version has broken artifacts uploads from appveyor to github. Should be ok now.

**Comment by variar** [comment] 2020-10-02 09:13
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746

**Closed by variar** 2020-10-02 09:13 UTC
Labels: status: ready for testing, type: bug
