### ISSUE TITLE
When warp text，some words are covered by scroll bar

### ISSUE THREAD

**Issue by modijafg** [variar/klogg#610] opened 2023-06-23 07:12 UTC
## version
klogg: `klogg 23.06.0.1419`
OS: Windows_NT x64 10.0.18363

## screencap
![1687502194288.jpg](https://github.com/variar/klogg/assets/65451470/d462f40d-62e0-462a-9ac2-9d8efce5a4cf)

## Gif
![1687504277230.gif](https://github.com/variar/klogg/assets/65451470/0a46fa70-e1df-4f60-a702-dc166f6340cb)

**Comment by variar** [comment] 2023-06-23 14:49
Thanks for reporting. Caused by #99. Need to account for that scroll bar width.

**Comment by variar** [comment] 2023-07-10 22:18
Fix is in 23.06.0.1538+

**Comment by modijafg** [comment] 2023-07-11 01:36
It works well now in latest pre-release version (23.06.0.1538), thanks for your work.

**Closed** 2023-07-11 01:36 UTC
Labels: type: bug, status: ready for testing
