### ISSUE TITLE
crash during move position in predefined filter dialog

### ISSUE THREAD

**Issue by shinewangy** [variar/klogg#368] opened 2021-07-29 08:32 UTC
Details for the issue
--------------------

#### What did you do?

-------------------------
Crash id:
6243fdeb-e2fb-4ef5-805b-08757211446e
-------------------------
Useful extra information
-------------------------
> Klogg version 21.07.0.1069 (built on 2021-07-25 from commit 7b5feec) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment] 2021-07-29 14:42
Thanks for reporting this. Could you describe what exactly were you doing before gettings this crash? I can't reproduce it locally for some reason.

**Comment by variar** [comment] 2021-07-31 08:45
Could be fixed in 21.07.0.1076

**Comment by shinewangy** [comment] 2021-08-02 02:02
Thank you



发自我的iPhone


------------------ Original ------------------
From: Anton Filimonov ***@***.***&gt;
Date: Sat,Jul 31,2021 4:46 PM
To: variar/klogg ***@***.***&gt;
Cc: shinewangy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [variar/klogg] crash during move position in predefined filter dialog (#368)





 
Could be fixed in 21.07.0.1076

**Closed** 2021-08-02 22:12 UTC
Labels: status: ready for testing, type: crash
