### ISSUE TITLE
Performance issue when reading/following large files over UNC

### ISSUE THREAD

**Issue by uponone** [variar/klogg#412] opened 2021-10-15 13:38 UTC
We are currently having performance issues reading large files over the network and tailing them. Files that are 100MB or more start to cause the app to become unusable.

I have dark mode enabled as well as some simple highlighters. Ignore case is enabled.

1. ERROR with Black background and Red foreground
2. WARN with White background and Orange foreground
3. DEBUG with Black background and Green foreground

baretail has the same highlighters enabled and has no problem reading the files in the same manner.

I also have the search filter disabled.

Machine is Windows 10 and server UNC is Windows Server 2012.

**Comment by variar** [comment] 2021-10-19 17:31
Check the latest dev version if possible.

20.12.0.813 with fast modification detection option should be better than without this option, but could still be slow because of the bug that has been fixed in dev versions.

**Comment by variar** [comment] 2021-11-04 20:39
Glad to hear it. Then it seems that the issue is resolved in dev builds. Will close for now.

**Closed by variar** 2021-11-04 20:39 UTC
Labels: status: need info
