### ISSUE TITLE
feature: support files with more than 2147483647 lines

### ISSUE THREAD

**Issue by 0x00Finch** [variar/klogg#339] opened 2021-06-14 08:05 UTC
When open, after indexing action, the scroll bar will disapear and the further content will no longer be readable

**Comment by variar** [comment] 2021-06-14 13:50
Which version of klogg are you using?

**Comment by 0x00Finch** [comment] 2021-06-14 19:00
@variar  I am using the newest release

**Comment by 0x00Finch** [comment] 2021-06-14 19:02
I will post the log later, I have to wait for indexing the lines. Thank you for detailed instruction on logging though.

**Comment by 0x00Finch** [comment] 2021-06-14 19:20
[klogg_2021-06-14_12-00-34_15772.log](https://github.com/variar/klogg/files/6650726/klogg_2021-06-14_12-00-34_15772.log)
[klogg_2021-06-14_12-01-19_4100.log](https://github.com/variar/klogg/files/6650727/klogg_2021-06-14_12-01-19_4100.log)

**Comment by variar** [comment] 2021-06-14 20:28
Thanks, I've downloaded the logs. Good thing, it looks like indexing speed is limited by hdd, not cpu. Bad thing, logs show index size of 8Gb, that should not happen. Can I have a copy of that file?

**Comment by 0x00Finch** [comment] 2021-06-14 21:30
@variar ok, bro. I will sent the magnet link to your gmail, is that ok to you?

**Comment by variar** [comment] 2021-06-14 21:37
Yes, that should work. Will need to get some free space :)

**Comment by 0x00Finch** [comment] 2021-06-14 21:38
thanks for paying attention on my feedback, looking forward to hear from you.

**Comment by variar** [comment] 2021-06-15 07:10
It turned out that the problem is not with the size of the file in bytes, but with total number of lines. Klogg can handle files up to 
4294967295 lines and your file has 8459060239 lines. There is no easy way to fix this without harming performance for vast majority of smaller files. However, there at least should be a check for this during indexing and some kind of warning that clearly describes a problem to users. 

For now you'll have to split the file so Klogg can handle its parts.

**Comment by variar** [comment] 2021-06-15 10:32
Actually it turned out that switching internal indexing/search structures to uint64 line numbers does not require too much changes. However, parts of Qt library is making me sad. For example, QAbstractSlider that is used for scrollbars can have only int32 number of steps.

**Comment by 0x00Finch** [comment] 2021-06-15 17:43
Thank you, at least we know the limit of klogg, a good thing.
btw, how can I split the file? is there any easy way to do that?

**Comment by 0x00Finch** [comment] 2021-06-15 18:06
I have found this app, I guess it will do the trick, https://www.microsoft.com/en-ca/p/large-text-viewer/9nblggh4mcm8

**Comment by 0x00Finch** [comment] 2021-06-15 19:40
Thank you

**Comment by variar** [comment] 2021-06-16 14:25
I've hacked a build that can handle huge files:
[klogg-21.06.0.1031-x64-portable.zip](https://github.com/variar/klogg/files/6663672/klogg-21.06.0.1031-x64-portable.zip)

This code is not included into master branch yet.

Indexing and searching works fine. But I am sure there are some issues that I've missed (scrolling, selection, jumping to beginning/end of document etc.).

@0x00Finch could you try it?

**Comment by 0x00Finch** [comment] 2021-06-17 02:02
I will give it a shot.

**Comment by 0x00Finch** [comment] 2021-06-17 02:50
@variar Hey man, it worked!! You definitely wanna add this feature into your schedule, trust me.
Saves a lot of pain when dealing with biggy

**Comment by 0x00Finch** [comment] 2021-06-17 02:52
scrolling, selection functions are not corrupted as far as I know

**Comment by variar** [comment] 2021-06-17 12:21
I've merged changes into main branch. Scrolling is strange at the end of file (allows to scroll past the end line), but this is a minor inconvenience compared to the benefits of this feature.

**Comment by 0x00Finch** [comment] 2021-06-17 19:22
yup

**Closed** 2021-06-17 20:59 UTC
Labels: status: need documentation, type: feature
