### ISSUE TITLE
Messed up line breaks

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#83] opened 2019-07-30 09:42 UTC
I managed to experience messed-up line breaks with 19.7.0.432 :

Here is what I observed:
![image](https://user-images.githubusercontent.com/11647984/62118598-40129200-b2be-11e9-8e15-ee8a5bc39b78.png)
Here is what it should have been (after closing & reopening the same file):
![image](https://user-images.githubusercontent.com/11647984/62118677-67695f00-b2be-11e9-95b1-9fa56eaf99ee.png)

I think the context here was that it is a local log file being shared on the network and updated by a remote computer.

Although I'm pretty sure the top part of the file (which is displayed) was already generated when I first opened the log file. So maybe the fact that new lines were added to the bottom somehow messed up the display off the top lines?

**Comment by variar** [comment] 2019-07-30 21:12
I hope this issue can be reproduced, but it can be tricky. Looks like it's time to setup symbol collection from CI builds and to add a button to generate error report with full process memory dump that can be analyzed in WinDbg to see the internal state of line ending index, search results and so on.

**Comment by variar** [comment] 2019-07-30 21:54
Looking through code I see one possible scenario for this issue. Firstly, if there is no \n character for the last line, then klogg adds fake one for futher uniform handling of each line. Secondly, when file is updated on disk, klogg starts indexing new data from the offset where it stopped last time. Combining these facts if there was no real \n at the end of the file, then klogg might start new line during index update. There is code that delets these fake \n charactes, I might have broken it during threading refactoring.

**Comment by wiz0u** [comment] 2019-07-31 07:50
I wonder if 'highlighters' have some related issues as well because in my first screenshot, the first "DEBUG" line (which seems not impacted by the line break issue) is not greyed out (by my highlighters) when it should have been

**Comment by variar** [comment] 2019-08-13 22:50
Could you check build 19.08.0.441? I've added check for the case when file has been modified in the already indexed range (comparing md5 for index data and new file data) and  full index operation should be performed if file was changed in the range of already built index.

**Comment by variar** [comment] 2019-08-14 16:22
On my windows box this leads to always doing full reindex. Looks like some kind of +-1 byte error.

**Comment by variar** [comment] 2019-08-31 05:45
Did some changes to partial hashing. @wiz0u  could  you check builds > 19.08.0.446?

**Comment by wiz0u** [comment] 2019-09-10 13:11
I'm checking on 19.9.0.454 now.
BTW did you mess with the Windows icon (top-left of the window and in the taskbar)?
because it looks ugly now. (a bit stretched horizontally, and blurry)

**Comment by variar** [comment] 2019-09-10 20:34
Thanks. I didn't change icons. But I did change qt theme engine on windows, this might cause icon deformation. I'm thinking of changing the icon to be less like original glogg, but c++ is easier than drawing :)

**Comment by wiz0u** [comment] 2019-09-10 22:22
I enjoy doing icons for my apps sometimes. I can make one for you (if you promised my art won't be deformed at standard 16x16 and 32x32 sizes 😃)

**Comment by wiz0u** [comment] 2019-09-11 08:14
I see a major issue with 19.9.0.454 with default settings :
When I search for a string, it seems to work, but after every 2 seconds (polling time), the search pane clears up with the error "File truncated on disk, previous search results are not valid anymore."
Note that the file I'm viewing is a log file that gets new line appended continuously.

The issue is so problematic, I might have to revert to a previous version of klogg until this is fixed.

```` 
[General]
version=1
mainFont.family=Consolas
mainFont.size=8
regexpType.main=0
regexpType.quickfind=2
quickfind.incremental=true
nativeFileWatch.enabled=true
polling.enabled=true
polling.intervalMs=2000
session.loadLast=true
logging.enableLogging=false
logging.verbosity=4
versionchecker.enabled=true
perf.useParallelSearch=true
perf.useSearchResultsCache=true
perf.searchResultsCacheLines=1000000
perf.indexReadBufferSizeMb=16
perf.searchReadBufferSizeLines=5000
perf.searchThreadPoolSize=0
perf.keepFileClosed=false
perf.useLineEndingCache=true
view.overviewVisible=true
view.lineNumbersVisibleInMain=false
view.lineNumbersVisibleInFiltered=true
view.minimizeToTray=false
defaultView.searchAutoRefresh=false
defaultView.searchIgnoreCase=false
defaultView.splitterSizes=400, 100
````

**Comment by variar** [comment] 2019-09-11 08:25
@wiz0u I moved it to separate issue #98. Could you enable logging and attach file form %TEMP%\klogg_*.log?

**Comment by variar** [comment] 2019-09-21 15:01
Closing for now. Please open again if the issue reproduced

**Closed by variar** 2019-09-21 15:01 UTC
Labels: bug, ready for testing
