### ISSUE TITLE
Klogg is getting slow every few seconds

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#172] opened 2020-01-24 16:33 UTC
For a few releases now, I start feeling some slowness from klogg.

For example, if I scroll the file up, every few seconds, I experience a bit of a freeze. And sometimes I observe the filepath box flashing like it is reindexing the whole file.
In my case the file is a UNC path (but LAN is not supposed to be sluggish) and the Polling interval is set to 2000ms.

This seems to happens quite regularly, but only if the file was changed, so possibly aligned with the 2 seconds interval.

So I wonder if you reload/reindex the whole file periodically, even though I'm watching a log file where data is only ever appended at the end (or cleared/reset but then file size would decrease)

**Comment by wiz0u** [comment] 2020-01-24 16:35
Also I should note that the log file in question is only 25 MB which should not be taking long to parse even if you reload it all.

**Comment by wiz0u** [comment] 2020-01-24 16:39
Note 2: when I click the Reload button, it takes a few seconds to reload the full file and the progress bar is visible, so it is not the same as the small freezes (1 sec or less) that I described

**Comment by dia-susca** [comment] 2020-01-29 13:14
Don't know if this helps or not, but last week I noticed klogg was using up about 3 GB of memory.  I monitored it for a few days after, but it never happened again.

**Comment by variar** [comment] 2020-02-12 18:45
That looks like the cost of correct reindexing for file changed in the middle. Every time file change is noticed (either from OS or via polling) klogg recalculates md5 of changed file up to the current last indexed position. If md5 is different from results calculated during original indexing then klogg understands that there were some changes in already indexed part and full reindexing is needed.

I don't know how this "in the middle" change can be determined without some checksum recalculation.

**Comment by wiz0u** [comment] 2020-02-12 19:19
Here are some ideas:

You could introduce a new threshold settings for big files...
If a file is bigger than XXX MB, then the md5 would cover only the first and last 4 KB of the file.
If after a change in a "big file" the file size was only increased and those 8 KB didn't change, it would be sufficient to determine the file was only appended, not changed in the middle.
(note that you would have to remember the offset for the previously hashed last 4 KB as this would change)

Alternatively, you could offer the user to configure a list of files extensions that are considered "log files" (only appended, unless file size is seen shrinking)

**Comment by variar** [comment] 2020-05-11 17:08
Switched from md5 to xxHash. On my machine xxHash is about 10 times faster.

@wiz0u thanks for the idea with head/tail blocks, I'll look into it. Cases when something is changed in the middle without affecting tail block should be rare.

**Comment by variar** [comment] 2020-09-18 20:41
xx3 hash proved to be unstable. I might coded it wrong, but switching to xx64 variant work ok. Still working on head/tail idea.

**Comment by variar** [comment] 2020-09-24 08:31
Implemented head/tail modification check. It is disabled by default and can be enabled in Options->File section.
Should be available in 20.9.0.678

**Comment by variar** [comment] 2020-10-02 09:16
Looks ok in my tests. Closing for now. Feel free to reopen if this issue reproduces in builds > 20.10.0.746

**Closed by variar** 2020-10-02 09:16 UTC
Labels: status: need documentation, status: ready for testing, type: bug
