### ISSUE TITLE
klogg crashes when opening multiple files from Windows Search in Windows Explorer

### ISSUE THREAD

**Issue by DVMirchev** [variar/klogg#329] opened 2021-06-01 10:19 UTC
Details for the issue
--------------------

#### What did you do?

1. Make a folder
2. Make several subfolders in it
3. Put a few  .log files in each folder
4. Open root folder with Windows Explorer
5. Search \*.\* 
6. Select several of the log files from the search results
7.  Right-click Open

It crashes almost every time regardless of whether klogg is running or not.

It does not crash if you double click or open a single file.

-------------------------
Crash id
bd613ba7-01c3-4f5c-a2a2-af3ac3e7f414
-------------------------
Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19042) [x86_64]
> and Qt 5.15.2

**Comment by variar** [comment] 2021-06-01 11:59
@DVMirchev thanks for reporting this. I was able to reproduce this issue locally. It is the same crash as in #228. That crash is in 3rdparty library. I've implemented a workaround so latest dev-builds of klogg don't crash anymore.

Now that you've provided steps to reproduce the issue reliably, I'll try to get it fixed in upstream library itself.

**Comment by variar** [comment] 2021-06-01 12:08
Upsream issue for reference itay-grudev/SingleApplication#128

**Comment by variar** [comment] 2021-06-01 19:22
Looks like this has been fixed in upstream several months ago.  I've pulled changes from master.

**Comment by variar** [comment] 2021-06-04 09:18
Merged fixes from upstream

**Closed by variar** 2021-06-04 09:18 UTC
Labels: status: ready for testing, type: crash
